/**
 * CLI: ingest the canonical CSV and print the import report.
 *   npm run import:report
 * This is the same pure importer the web app calls; running it here gives the
 * "import report" deliverable without needing the UI. Writes IMPORT_REPORT.md.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { importCsv } from "../src/core/importer";
import { DEFAULT_MEMBERSHIP } from "../src/core/membership";
import { formatPaise } from "../src/core/money";

const path = process.argv[2] ?? "data/expenses_export.csv";
const csv = readFileSync(path, "utf8");

const report = importCsv(csv, {
  filename: path.split("/").pop() ?? path,
  baseCurrency: "INR",
  membership: DEFAULT_MEMBERSHIP,
  defaultYear: 2026,
});

const lines: string[] = [];
const out = (s = "") => lines.push(s);

out(`# Import Report — ${report.filename}`);
out();
out(`Generated by \`npm run import:report\` (the same importer the web app uses).`);
out();
out(`| Metric | Count |`);
out(`| --- | --- |`);
out(`| Data rows read | ${report.totalRows} |`);
out(`| Expenses imported | ${report.summary.expenses} |`);
out(`| Settlements recorded | ${report.summary.settlements} |`);
out(`| Rows skipped | ${report.summary.skipped} |`);
out(`| Anomalies detected | ${report.summary.anomalies} |`);
out(`| Changes needing approval | ${report.summary.pendingApprovals} |`);
out();

out(`## Anomalies (every problem detected, and what the importer did)`);
out();
out(`| Row | Code | Severity | Review | Action | Detail |`);
out(`| --- | --- | --- | --- | --- | --- |`);
for (const a of report.anomalies.sort((x, y) => (x.sourceRow ?? 0) - (y.sourceRow ?? 0))) {
  out(`| ${a.sourceRow ?? "-"} | ${a.code} | ${a.severity} | ${a.reviewStatus} | ${a.action} | ${a.message.replace(/\|/g, "\\|")} |`);
}
out();

out(`## Settlements (reclassified from expense rows)`);
out();
for (const s of report.settlements) {
  out(`- Row ${s.sourceRow}: **${s.payer} → ${s.payee}** ${formatPaise(s.amountPaise)} — ${s.note}`);
}
out();

out(`## Skipped rows (held out of balances)`);
out();
for (const s of report.skipped) {
  out(`- Row ${s.sourceRow}: ${s.reason}`);
}
out();

out(`## Imported expenses (final, after dedupe / FX / membership)`);
out();
out(`| Row | Date | Description | Paid by | Amount | Split | Participants |`);
out(`| --- | --- | --- | --- | --- | --- | --- |`);
for (const e of report.expenses) {
  const fx = e.originalCurrency !== "INR" ? ` (${e.originalCurrency} ${(e.originalAmountPaise / 100).toFixed(2)})` : "";
  out(`| ${e.sourceRow} | ${e.date} | ${e.description} | ${e.paidBy} | ${formatPaise(e.amountPaise)}${fx} | ${e.splitType} | ${Object.keys(e.shares).join(", ")} |`);
}
out();

const md = lines.join("\n");
writeFileSync("IMPORT_REPORT.md", md);

// Also print a terse summary to the console.
console.log(md);
console.error(
  `\n[import] ${report.summary.expenses} expenses, ${report.summary.settlements} settlements, ` +
    `${report.summary.skipped} skipped, ${report.summary.anomalies} anomalies ` +
    `(${report.summary.pendingApprovals} need approval). Wrote IMPORT_REPORT.md`,
);
